### ISSUE TITLE
Unable to install from Debian meta-package

### ISSUE THREAD

**Issue by tony2guo** [2b-t/docker-realtime#10]
In [Installation from Debian package]( https://github.com/2b-t/linux-realtime/blob/main/doc/PreemptRt.md#122-installation-from-debian-package
), the script downloads a meta-package. Installing the package will have dependency error:
`
sudo dpkg -i linux-image-rt-amd64_6.12.6-1_amd64.deb
`
```
Preparing to unpack linux-image-rt-amd64_6.12.6-1_amd64.deb ...
Unpacking linux-image-rt-amd64 (6.12.6-1) over (6.12.6-1) ...
dpkg: dependency problems prevent configuration of linux-image-rt-amd64:
 linux-image-rt-amd64 depends on linux-image-6.12.6-rt-amd64 (= 6.12.6-1); however:
  Package linux-image-6.12.6-rt-amd64 is not installed.

dpkg: error processing package linux-image-rt-amd64 (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 linux-image-rt-amd64
```
` sudo apt-get install -f` will remove the linux-image-rt-amd64 package.
```
The following packages will be REMOVED:
  linux-image-rt-amd64
```
Instead of using the meta-package, I successfully downloaded and installed the patched kernel package from [here](https://packages.debian.org/trixie/linux-image-6.12.5-rt-amd64).

**Comment by 2b-t** [comment]
_Hi @tony2guo,_
Thanks for bringing this to my attention. I changed the script now to download the patched kernel package that the meta-package points to instead (perhaps I should also make it download the [kernel headers](https://packages.debian.org/trixie/linux-headers-rt-amd64) as well). I just tested it and it seems to work fine now. Let me know if it works for you too.
_Thanks again!_

**Comment by tony2guo** [comment]
Thank you for the fix! I tested it, and it works for me.
